### ISSUE TITLE
EasyFxml for commercial use 

### ISSUE THREAD

**Issue by hubertstruminski** [Tristan971/EasyFXML#39]
Is EasyFxml free for commercial use ?

**Comment by Tristan971** [comment]
Hi,

As per the https://github.com/Tristan971/EasyFXML/blob/master/LICENSE it is under the Apache 2.0 license which does allow free commercial use :slightly_smiling_face: 

It doesn't even require contributing back the changes you made privately (although that would be hugely appreciated as I do not have a lot of time to cater to it these days).

The only thing it seems to require is some kind of notice of usage of the project somewhere (like an acknowledgments panel or something?) but I'm no lawyer and I don't personally have the will to try to enforce these things to be honest

Hope that answers
